// <auto-generated />
using System;
using DevPrime.State.Connections;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(ConnectionEF))]
    [Migration("20240710183249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevPrime.State.Repositories.Customer.Model.Address", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressId")
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .HasColumnType("text");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("DevPrime.State.Repositories.Customer.Model.Customer", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddressID")
                        .HasColumnType("uuid");

                    b.Property<int>("CustomerClass")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text");

                    b.Property<int>("CustomerType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentCustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartnerId")
                        .HasColumnType("text");

                    b.HasKey("TenantId");

                    b.HasIndex("AddressID");

                    b.HasIndex("ParentCustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("DevPrime.State.Repositories.Customer.Model.Customer", b =>
                {
                    b.HasOne("DevPrime.State.Repositories.Customer.Model.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID");

                    b.HasOne("DevPrime.State.Repositories.Customer.Model.Customer", "ParentCustomer")
                        .WithMany()
                        .HasForeignKey("ParentCustomerId");

                    b.Navigation("Address");

                    b.Navigation("ParentCustomer");
                });
#pragma warning restore 612, 618
        }
    }
}
