global using System;
global using System.Collections.Generic;
global using System.Linq;
global using Application.EventHandlers.Customer;
global using Application.Interfaces.Adapters.Extensions;
global using Application.Interfaces.Adapters.State;
global using Application.Interfaces.Services;
global using Application.Services.Customer.Model;
// global using Application.Services.Customer.Model.Query;
// global using Application.Services.Customer.Model.Result;
global using DevPrime.Stack.Foundation;
global using DevPrime.Stack.Foundation.Application;
global using Domain.Aggregates.Customer.Events;
